#!/usr/bin/env python

import Tkinter
import ScrolledText


def update_image():
    text = get(start, end)

class MeseqGui(object):

    def __init__(self):
        self.root = Tkinter.Tk(className="MeseqGui")
        self.paned_window = Tkinter.PanedWindow(self.root, orient=Tkinter.HORIZONTAL)
        self.editor = ScrolledText.ScrolledText(self.paned_window, wrap=Tkinter.N)
        self.image = Tkinter.Label(self.paned_window)
        self.paned_window.add(self.editor)
        self.paned_window.add(self.image)

    def update_image(self):
        img = Tkinter.PhotoImage(file="t.msq.png")
        self.image.config(image=img)
        self.img_ref = img # keep a reference

    def display(self):
        self.update_image()
        self.paned_window.pack(side=Tkinter.TOP, expand=Tkinter.Y, fill=Tkinter.BOTH, pady=2, padx=2)
        self.root.mainloop()

msqgui = MeseqGui()
msqgui.display()


